export const ADD_LOADER = "ADD_LOADER";
export const REMOVE_LOADER = "REMOVE_LOADER";
export const ADD_REQUEST = "ADD_REQUEST";
export const REMOVE_REQUEST = "REMOVE_REQUEST";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
